// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;
using PredictionOfClothingML.Model;

namespace PredictionOfClothingML.Model
{
    public class ConsumeModel
    {
        public static ModelOutput Predict(ModelInput input)
        {
            MLContext mlContext = new MLContext();

            string modelPath = @"C:\Users\yakup\AppData\Local\Temp\MLVSTools\PredictionOfClothingML\PredictionOfClothingML.Model\MLModel.zip";
            ITransformer mlModel = mlContext.Model.Load(modelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
            ModelOutput result = predEngine.Predict(input);
            return result;
        }
    }
}
